import type { PullRequest } from '../../src/github/pull-request.js'

export function pullRequestFixture(overrides: Partial<PullRequest> = {}): PullRequest {
  return {
    repo: 'acme/shop',
    number: 12,
    url: 'https://github.com/acme/shop/pull/12',
    title: 'Let users spend crystals',
    description: 'Adds a spend endpoint.',
    author: 'octocat',
    state: 'open',
    draft: false,
    baseRef: 'main',
    baseSha: '0000000000000000000000000000000000000000',
    headRef: 'feature/spend',
    headSha: 'a1b2c3d4e5f60718293a4b5c6d7e8f9012345678',
    fromFork: false,
    private: false,
    stats: { changedFiles: 2, additions: 15, deletions: 1, commits: 1 },
    diff: [
      'diff --git a/src/shop.ts b/src/shop.ts',
      'index 1111111..2222222 100644',
      '--- a/src/shop.ts',
      '+++ b/src/shop.ts',
      '@@ -1,4 +1,12 @@',
      " import { db } from './db'",
      '+',
      '+export async function spend(userId: string, amount: number) {',
      '+  const user = await db.user.find(userId)',
      "+  if (user.crystals < amount) throw new Error('insufficient crystals')",
      '+  await db.user.update(userId, { crystals: user.crystals - amount })',
      '+  return user.crystals - amount',
      '+}',
      '+',
      ' export function balance(userId: string) {',
      '   return db.user.find(userId).crystals',
      ' }',
      '',
    ].join('\n'),
    ...overrides,
  }
}
